# Rime default settings
# encoding: utf-8


# 要比共享目录的同名文件的 config_version 大才可以生效
config_version: '2025-12-15'


# 方案列表
schema_list:
  - schema: yoyo-bm       # 纯形·北冥（单字派）
  - schema: yoyo-wx       # 纯形·无相（主词派）
  - schema: yoyo-bm-km    # 纯形·北冥·空明（空明拳指法）
  - schema: yoyo-wx-km    # 纯形·无相·空明（空明拳指法）
  - schema: yoyo-yx       # 音形·呦呦
  - schema: yoyo-yx-hm   # 音形·呦呦（寒梅指法）
  - schema: yoyo-practice # 纯形字根练习

# 菜单
menu:
  page_size: 6  # 候选词个数
  alternative_select_labels: [ ⒈, ⒉, ⒊, ⒋, ⒌, ⒍, ⒎, ⒏, ⒐, ⒑, ⒒, ⒓, ⒔, ⒕, ⒖, ⒗, ⒘, ⒙, ⒚, ⒛ ]  # 修改候选项标签


# 方案选单相关
switcher:
  caption: 「方案选单」
  hotkeys:
    - Control+Tab
    - Alt+grave